/** 星座英文名 -> 中文名映射（当前精选星表用到的部分）。 */
export const CONSTELLATION_ZH: Record<string, string> = {
  Andromeda: '仙女座',
  Aquila: '天鹰座',
  Aries: '白羊座',
  Auriga: '御夫座',
  Boötes: '牧夫座',
  'Canis Major': '大犬座',
  'Canis Minor': '小犬座',
  Carina: '船底座',
  Centaurus: '半人马座',
  Cetus: '鲸鱼座',
  Crux: '南十字座',
  Cygnus: '天鹅座',
  Eridanus: '波江座',
  Gemini: '双子座',
  Hydra: '长蛇座',
  Leo: '狮子座',
  Lyra: '天琴座',
  Ophiuchus: '蛇夫座',
  Orion: '猎户座',
  Pavo: '孔雀座',
  Perseus: '英仙座',
  'Piscis Austrinus': '南鱼座',
  Sagittarius: '人马座',
  Scorpius: '天蝎座',
  Taurus: '金牛座',
  'Triangulum Australe': '南三角座',
  'Ursa Major': '大熊座',
  'Ursa Minor': '小熊座',
  Virgo: '室女座',
};
