/**
 * 星座映射。以 IAU 3 字母缩写为主键，覆盖全 88 星座。
 * HYG 星表的 `con` 列即为 3 字母缩写；由此派生「全英文名 → 中文名」映射，
 * 兼容手写 60 颗精选星（其 constellation 用全英文名）。
 */

/** IAU 3 字母缩写 → { 全英文名, 中文名 }。覆盖全 88 星座。 */
export const CONSTELLATION_ABBR: Record<string, { en: string; zh: string }> = {
  And: { en: 'Andromeda', zh: '仙女座' },
  Ant: { en: 'Antlia', zh: '唧筒座' },
  Aps: { en: 'Apus', zh: '天燕座' },
  Aqr: { en: 'Aquarius', zh: '宝瓶座' },
  Aql: { en: 'Aquila', zh: '天鹰座' },
  Ara: { en: 'Ara', zh: '天坛座' },
  Ari: { en: 'Aries', zh: '白羊座' },
  Aur: { en: 'Auriga', zh: '御夫座' },
  Boo: { en: 'Boötes', zh: '牧夫座' },
  Cae: { en: 'Caelum', zh: '雕具座' },
  Cam: { en: 'Camelopardalis', zh: '鹿豹座' },
  Cnc: { en: 'Cancer', zh: '巨蟹座' },
  CVn: { en: 'Canes Venatici', zh: '猎犬座' },
  CMa: { en: 'Canis Major', zh: '大犬座' },
  CMi: { en: 'Canis Minor', zh: '小犬座' },
  Cap: { en: 'Capricornus', zh: '摩羯座' },
  Car: { en: 'Carina', zh: '船底座' },
  Cas: { en: 'Cassiopeia', zh: '仙后座' },
  Cen: { en: 'Centaurus', zh: '半人马座' },
  Cep: { en: 'Cepheus', zh: '仙王座' },
  Cet: { en: 'Cetus', zh: '鲸鱼座' },
  Cha: { en: 'Chamaeleon', zh: '蝘蜓座' },
  Cir: { en: 'Circinus', zh: '圆规座' },
  Col: { en: 'Columba', zh: '天鸽座' },
  Com: { en: 'Coma Berenices', zh: '后发座' },
  CrA: { en: 'Corona Australis', zh: '南冕座' },
  CrB: { en: 'Corona Borealis', zh: '北冕座' },
  Crv: { en: 'Corvus', zh: '乌鸦座' },
  Crt: { en: 'Crater', zh: '巨爵座' },
  Cru: { en: 'Crux', zh: '南十字座' },
  Cyg: { en: 'Cygnus', zh: '天鹅座' },
  Del: { en: 'Delphinus', zh: '海豚座' },
  Dor: { en: 'Dorado', zh: '剑鱼座' },
  Dra: { en: 'Draco', zh: '天龙座' },
  Equ: { en: 'Equuleus', zh: '小马座' },
  Eri: { en: 'Eridanus', zh: '波江座' },
  For: { en: 'Fornax', zh: '天炉座' },
  Gem: { en: 'Gemini', zh: '双子座' },
  Gru: { en: 'Grus', zh: '天鹤座' },
  Her: { en: 'Hercules', zh: '武仙座' },
  Hor: { en: 'Horologium', zh: '时钟座' },
  Hya: { en: 'Hydra', zh: '长蛇座' },
  Hyi: { en: 'Hydrus', zh: '水蛇座' },
  Ind: { en: 'Indus', zh: '印第安座' },
  Lac: { en: 'Lacerta', zh: '蝎虎座' },
  Leo: { en: 'Leo', zh: '狮子座' },
  LMi: { en: 'Leo Minor', zh: '小狮座' },
  Lep: { en: 'Lepus', zh: '天兔座' },
  Lib: { en: 'Libra', zh: '天秤座' },
  Lup: { en: 'Lupus', zh: '豺狼座' },
  Lyn: { en: 'Lynx', zh: '天猫座' },
  Lyr: { en: 'Lyra', zh: '天琴座' },
  Men: { en: 'Mensa', zh: '山案座' },
  Mic: { en: 'Microscopium', zh: '显微镜座' },
  Mon: { en: 'Monoceros', zh: '麒麟座' },
  Mus: { en: 'Musca', zh: '苍蝇座' },
  Nor: { en: 'Norma', zh: '矩尺座' },
  Oct: { en: 'Octans', zh: '南极座' },
  Oph: { en: 'Ophiuchus', zh: '蛇夫座' },
  Ori: { en: 'Orion', zh: '猎户座' },
  Pav: { en: 'Pavo', zh: '孔雀座' },
  Peg: { en: 'Pegasus', zh: '飞马座' },
  Per: { en: 'Perseus', zh: '英仙座' },
  Phe: { en: 'Phoenix', zh: '凤凰座' },
  Pic: { en: 'Pictor', zh: '绘架座' },
  Psc: { en: 'Pisces', zh: '双鱼座' },
  PsA: { en: 'Piscis Austrinus', zh: '南鱼座' },
  Pup: { en: 'Puppis', zh: '船尾座' },
  Pyx: { en: 'Pyxis', zh: '罗盘座' },
  Ret: { en: 'Reticulum', zh: '网罟座' },
  Sge: { en: 'Sagitta', zh: '天箭座' },
  Sgr: { en: 'Sagittarius', zh: '人马座' },
  Sco: { en: 'Scorpius', zh: '天蝎座' },
  Scl: { en: 'Sculptor', zh: '玉夫座' },
  Sct: { en: 'Scutum', zh: '盾牌座' },
  Ser: { en: 'Serpens', zh: '巨蛇座' },
  Sex: { en: 'Sextans', zh: '六分仪座' },
  Tau: { en: 'Taurus', zh: '金牛座' },
  Tel: { en: 'Telescopium', zh: '望远镜座' },
  Tri: { en: 'Triangulum', zh: '三角座' },
  TrA: { en: 'Triangulum Australe', zh: '南三角座' },
  Tuc: { en: 'Tucana', zh: '杜鹃座' },
  UMa: { en: 'Ursa Major', zh: '大熊座' },
  UMi: { en: 'Ursa Minor', zh: '小熊座' },
  Vel: { en: 'Vela', zh: '船帆座' },
  Vir: { en: 'Virgo', zh: '室女座' },
  Vol: { en: 'Volans', zh: '飞鱼座' },
  Vul: { en: 'Vulpecula', zh: '狐狸座' },
};

/**
 * 星座全英文名 → 中文名映射，由 CONSTELLATION_ABBR 派生，避免重复维护。
 * 手写 60 颗精选星的 constellation 用全英文名，可继续用此表查中文。
 */
export const CONSTELLATION_ZH: Record<string, string> = Object.fromEntries(
  Object.values(CONSTELLATION_ABBR).map((c) => [c.en, c.zh]),
);
